engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
        languages:
            - php
            - javascript
            - scss
ratings:
  paths:
    - app/**
    - src/**
    - web/**
    - "**.php"
exclude_paths:
    - spec/**/*
    - "**/vendor/**/*"
    - "**/var/**/*"
    - "web/*.php"