engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
   enabled: true
   config:
      languages:
      - php
      - javascript
ratings:
  paths:
  - app/**
  - src/**
  - web/assets/**/*
exclude_paths:
- spec/**/*
- vendor/**/*
- var/*.php
- web/*.php
- app/*.php
- nbroject/**/*
- tests/**/*