dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
  - 'nightly'
env:
matrix:
  allow_failures:
  - php: nightly
services:
- mysql
    
install:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - sudo lsof /var/run/mysqld/mysqld.sock
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS symfony;'
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:schema:update

before_script:
  - php bin/console server:start
  
script:
  - ./vendor/bin/codecept run acceptance
