security:
    resource: "@SecurityBundle/Controller/"
    type:     annotation
    prefix:   /

file:
    resource: "@FileBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout

