# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:    
    encoders:
        Blogger\UserBundle\Entity\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        our_db_provider:
            entity:
                class: UserBundle:User
                property: username
 
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            pattern: ^/
            
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            
            provider: our_db_provider

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login: 
                login_path: login
                check_path: login
       
            logout:
                path: /logout
                target: /   
            
                    
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/news/edit/, roles: ROLE_EDITOR }
        - { path: ^/news/create, roles: ROLE_EDITOR }
        - { path: ^/news/delete/, roles: ROLE_ADMIN }
        
        
    role_hierarchy:
        ROLE_EDITOR: ROLE_USER
        ROLE_ADMIN: ROLE_EDITOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
