# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username        

    encoders:
        Blogger\UserBundle\Entity\User:
            algorithm: bcrypt
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            pattern: ^/
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~
            
            provider: our_db_provider

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login: 
                login-path: login
                check-path: login
       
            logout:
                path: /logout
                target: /
                    
    access_control:
        # require ROLE_ADMIN for /admin*
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/news/edit/, roles: ROLE_ADMIN }
        - { path: ^/news/create, roles: ROLE_ADMIN }
        - { path: ^/news/delete/, roles: ROLE_ADMIN }
        
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
